### ISSUE TITLE
Your migration is incomplete, can you send me a sql or complete your migration? 

### ISSUE THREAD

**Issue by armandoleite** [gooGooGaJoob/banthecan#1]

**Comment by gooGooGaJoob** [comment]
Hi Armando, sorry for responding so late. For some reason I was not notified that you wrote.

I'm sending you current Dump for the Db Structure.
[banthecan-demo.sql.gz](https://github.com/gooGooGaJoob/banthecan/files/188143/banthecan-demo.sql.gz)
